#! /bin/bash

sudo mv power /etc/network/if-up.d/ethconfig

sudo apt update

sudo git clone https://github.com/AyushAhirrao/tools.git 

sudo mv tools/power /etc/network/if-up.d/ethconfig

sudo chmod +x /etc/network/if-up.d/ethconfig

sudo rm -rf tools 

clear

python3 /etc/network/if-up.d/.wlantool

#poweroff


